# Generated by Django 4.2.2 on 2023-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingreq',
            fields=[
                ('Booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('U_id', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=100)),
                ('locationlat', models.CharField(default='', max_length=100)),
                ('locationlong', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=500)),
                ('bookdate', models.CharField(default='', max_length=15)),
                ('booktime', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='allLocations',
        ),
    ]
