# Generated by Django 4.2.2 on 2023-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0002_bookingreq_delete_alllocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='assistant',
            fields=[
                ('Ass_id', models.AutoField(primary_key=True, serialize=False)),
                ('assname', models.CharField(default='', max_length=100)),
                ('assfullname', models.CharField(default='', max_length=100)),
                ('assemail', models.EmailField(max_length=254)),
                ('assage', models.IntegerField()),
                ('assdate_of_birth', models.DateField()),
                ('homelocationlat', models.CharField(default='', max_length=100)),
                ('homelocationlong', models.CharField(default='', max_length=100)),
                ('contact_number', models.CharField(default='', max_length=15)),
                ('registerdOn', models.CharField(default='', max_length=100)),
                ('ratings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='serve_req',
            fields=[
                ('serve_req_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ass_id', models.IntegerField(default=0)),
                ('Booking_id', models.IntegerField(default=0)),
                ('assname', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=15)),
                ('currentlocationlat', models.CharField(default='', max_length=100)),
                ('currentlocationlong', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('serveActivedate', models.CharField(default='', max_length=15)),
                ('serveActivetime', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='bookingreq',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingreq',
            name='status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
