# Generated by Django 4.2.2 on 2023-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0003_assistant_serve_req_bookingreq_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='assstate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingreq',
            name='slug',
            field=models.CharField(default='', max_length=15),
        ),
    ]
