# Generated by Django 4.2.2 on 2023-09-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0004_assistant_assstate_bookingreq_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingreq',
            name='slug',
        ),
    ]
