# Generated by Django 4.2.2 on 2023-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0005_remove_bookingreq_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalchat',
            fields=[
                ('chat_id', models.IntegerField(default=0)),
                ('Booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(default='', max_length=1000)),
                ('username', models.CharField(default='', max_length=100)),
                ('bookdate', models.CharField(default='', max_length=15)),
                ('booktime', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='bookingreq',
            name='assistedbyAss_id',
            field=models.IntegerField(default=0),
        ),
    ]
