# Generated by Django 4.2.2 on 2023-09-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0006_personalchat_bookingreq_assistedbyass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchat',
            name='Booking_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalchat',
            name='chat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
