# Generated by Django 4.2.2 on 2023-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0007_alter_personalchat_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assreviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_id', models.IntegerField(default=0)),
                ('message', models.CharField(default='', max_length=1000)),
                ('username', models.CharField(default='', max_length=100)),
                ('review_date', models.CharField(default='', max_length=15)),
                ('review_time', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
