# Generated by Django 4.2.2 on 2023-10-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0009_assreviews_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assreviews',
            old_name='Booking_id',
            new_name='Ass_id',
        ),
        migrations.AddField(
            model_name='assreviews',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
    ]
