# Generated by Django 4.2.2 on 2023-10-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0010_rename_booking_id_assreviews_ass_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
